from __future__ import annotations

import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime
from typing import Any, Dict, Iterable, Iterator, List, Sequence

from .config import CITY, COMPETITOR, DATABASE_URL, DB_PATH, OWN_COMPANY, ensure_dirs
from .models import Flat, House

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - optional in local sqlite mode
    psycopg = None
    dict_row = None


IS_POSTGRES = bool(DATABASE_URL)


class _CursorResult:
    def __init__(self, cursor: Any) -> None:
        self._cursor = cursor

    def fetchone(self) -> Any:
        return self._cursor.fetchone()

    def fetchall(self) -> List[Any]:
        return self._cursor.fetchall()

    @property
    def lastrowid(self) -> Any:
        return getattr(self._cursor, "lastrowid", None)

    def __iter__(self):
        return iter(self._cursor)


class DBConnection:
    def __init__(self, raw: Any, backend: str) -> None:
        self._raw = raw
        self.backend = backend

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> _CursorResult:
        if self.backend == "sqlite":
            return _CursorResult(self._raw.execute(sql, params or ()))
        cur = self._raw.cursor()
        cur.execute(_pg_sql(sql), params or ())
        return _CursorResult(cur)

    def executemany(self, sql: str, rows: Iterable[Sequence[Any]]) -> _CursorResult:
        rows = list(rows)
        if self.backend == "sqlite":
            return _CursorResult(self._raw.executemany(sql, rows))
        cur = self._raw.cursor()
        cur.executemany(_pg_sql(sql), rows)
        return _CursorResult(cur)

    def executescript(self, script: str) -> None:
        if self.backend == "sqlite":
            self._raw.executescript(script)
            return
        cur = self._raw.cursor()
        for statement in _split_sql_script(script):
            cur.execute(statement)

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()


def _pg_sql(sql: str) -> str:
    return sql.replace("?", "%s")


def _split_sql_script(script: str) -> List[str]:
    return [part.strip() for part in script.split(";") if part.strip()]


def _placeholders(count: int) -> str:
    token = "%s" if IS_POSTGRES else "?"
    return ",".join(token for _ in range(count))


@contextmanager
def connect() -> Iterator[DBConnection]:
    ensure_dirs()
    if IS_POSTGRES:
        if psycopg is None:
            raise RuntimeError("DATABASE_URL задан, но пакет psycopg не установлен.")
        raw = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        conn = DBConnection(raw, "postgres")
    else:
        raw = sqlite3.connect(DB_PATH)
        raw.row_factory = sqlite3.Row
        conn = DBConnection(raw, "sqlite")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def init_db() -> None:
    with connect() as conn:
        conn.executescript(_schema_sql(conn.backend))
        _migrate_columns(conn)
        _seed_reference_data(conn)


def _schema_sql(backend: str) -> str:
    serial = "INTEGER PRIMARY KEY AUTOINCREMENT" if backend == "sqlite" else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return f"""
        CREATE TABLE IF NOT EXISTS developers (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            type TEXT NOT NULL DEFAULT 'competitor',
            region TEXT,
            source_url TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS projects (
            id TEXT PRIMARY KEY,
            developer_id TEXT NOT NULL,
            name TEXT NOT NULL,
            address TEXT,
            region TEXT,
            source_url TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS buildings (
            id TEXT PRIMARY KEY,
            project_id TEXT NOT NULL,
            name TEXT NOT NULL,
            source_id TEXT,
            source_url TEXT,
            total_apartments_collected INTEGER,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS refresh_runs (
            id {serial},
            started_at TEXT NOT NULL,
            finished_at TEXT,
            status TEXT NOT NULL,
            message TEXT,
            source_total INTEGER,
            collected_total INTEGER
        );

        CREATE TABLE IF NOT EXISTS houses (
            house_id TEXT PRIMARY KEY,
            project_id TEXT NOT NULL,
            project_name TEXT NOT NULL,
            house_name TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS flats (
            flat_id TEXT PRIMARY KEY,
            developer_id TEXT,
            code TEXT NOT NULL,
            project_id TEXT NOT NULL,
            project_name TEXT NOT NULL,
            house_id TEXT NOT NULL,
            house_name TEXT NOT NULL,
            rooms TEXT NOT NULL,
            area REAL,
            floor INTEGER,
            price REAL,
            price_per_sqm REAL,
            status TEXT NOT NULL DEFAULT 'in_sale',
            url TEXT NOT NULL,
            image_url TEXT NOT NULL,
            layout_uuid TEXT NOT NULL,
            layout_group_id TEXT,
            first_seen_at TEXT,
            last_seen_at TEXT,
            created_at TEXT,
            updated_at TEXT
        );

        CREATE TABLE IF NOT EXISTS layout_groups (
            group_id TEXT PRIMARY KEY,
            developer_id TEXT,
            project_id TEXT,
            house_id TEXT NOT NULL,
            rooms TEXT NOT NULL,
            layout_no INTEGER NOT NULL,
            representative_image_url TEXT NOT NULL,
            representative_local_path TEXT,
            hash TEXT,
            flat_count INTEGER NOT NULL,
            flat_ids_json TEXT NOT NULL,
            min_area REAL,
            max_area REAL,
            avg_area REAL,
            min_price REAL,
            max_price REAL,
            avg_price REAL,
            avg_price_per_sqm REAL,
            layout_quality_score REAL,
            created_at TEXT,
            updated_at TEXT
        );

        CREATE TABLE IF NOT EXISTS snapshots (
            id {serial},
            developer_id TEXT NOT NULL,
            source TEXT NOT NULL,
            collected_at TEXT NOT NULL,
            status TEXT NOT NULL,
            projects_count INTEGER NOT NULL DEFAULT 0,
            buildings_count INTEGER NOT NULL DEFAULT 0,
            apartments_count INTEGER NOT NULL DEFAULT 0,
            layout_groups_count INTEGER NOT NULL DEFAULT 0,
            raw_payload_path TEXT,
            raw_payload_json TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS apartment_snapshots (
            id {serial},
            snapshot_id INTEGER NOT NULL,
            apartment_id TEXT NOT NULL,
            price REAL,
            price_per_sqm REAL,
            area REAL,
            floor INTEGER,
            status TEXT NOT NULL,
            layout_group_id TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS layout_tags (
            id {serial},
            name TEXT NOT NULL UNIQUE,
            description TEXT
        );

        CREATE TABLE IF NOT EXISTS layout_group_tags (
            layout_group_id TEXT NOT NULL,
            tag_id INTEGER NOT NULL,
            confidence REAL,
            source TEXT NOT NULL DEFAULT 'manual',
            created_at TEXT NOT NULL,
            PRIMARY KEY (layout_group_id, tag_id)
        );

        CREATE TABLE IF NOT EXISTS manual_layout_merges (
            id {serial},
            house_id TEXT NOT NULL,
            rooms TEXT NOT NULL,
            target_group_key TEXT NOT NULL,
            source_group_key TEXT NOT NULL,
            note TEXT,
            created_at TEXT NOT NULL,
            UNIQUE (house_id, rooms, target_group_key, source_group_key)
        );
    """


def _table_columns(conn: DBConnection, table: str) -> set[str]:
    if conn.backend == "sqlite":
        return {row["name"] for row in conn.execute(f"PRAGMA table_info({table})")}
    return {
        row["column_name"]
        for row in conn.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = ?
            """,
            (table,),
        )
    }


def _migrate_columns(conn: DBConnection) -> None:
    columns = {table: _table_columns(conn, table) for table in ("developers", "flats", "layout_groups")}
    developer_columns = {
        "type": "TEXT NOT NULL DEFAULT 'competitor'",
    }
    for name, ddl in developer_columns.items():
        if name not in columns["developers"]:
            conn.execute(f"ALTER TABLE developers ADD COLUMN {name} {ddl}")
    flat_columns = {
        "developer_id": "TEXT",
        "price_per_sqm": "REAL",
        "status": "TEXT NOT NULL DEFAULT 'in_sale'",
        "layout_group_id": "TEXT",
        "first_seen_at": "TEXT",
        "last_seen_at": "TEXT",
        "created_at": "TEXT",
        "updated_at": "TEXT",
    }
    for name, ddl in flat_columns.items():
        if name not in columns["flats"]:
            conn.execute(f"ALTER TABLE flats ADD COLUMN {name} {ddl}")

    group_columns = {
        "developer_id": "TEXT",
        "project_id": "TEXT",
        "min_area": "REAL",
        "max_area": "REAL",
        "avg_area": "REAL",
        "min_price": "REAL",
        "max_price": "REAL",
        "avg_price": "REAL",
        "avg_price_per_sqm": "REAL",
        "layout_quality_score": "REAL",
        "created_at": "TEXT",
        "updated_at": "TEXT",
    }
    for name, ddl in group_columns.items():
        if name not in columns["layout_groups"]:
            conn.execute(f"ALTER TABLE layout_groups ADD COLUMN {name} {ddl}")


def _seed_reference_data(conn: DBConnection) -> None:
    now = datetime.now().isoformat(timespec="seconds")
    developers = [
        ("zhcom", COMPETITOR, "competitor", CITY, "https://zhcom.ru/kirov/flats?limit=16"),
        ("sretensky", "Сретенский посад", "competitor", CITY, "https://xn--b1aakjajcf0abexf2n.xn--p1ai/plans#plans"),
        ("kssk", OWN_COMPANY, "own", CITY, "https://объектив.рф/ProjectCards"),
    ]
    conn.executemany(
        """
        INSERT INTO developers (id, name, type, region, source_url, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            name = excluded.name,
            type = excluded.type,
            region = excluded.region,
            source_url = excluded.source_url,
            updated_at = excluded.updated_at
        """,
        [
            (developer_id, name, developer_type, region, source_url, now, now)
            for developer_id, name, developer_type, region, source_url in developers
        ],
    )
    conn.execute("UPDATE flats SET developer_id = 'zhcom' WHERE developer_id IS NULL")
    conn.execute("UPDATE layout_groups SET developer_id = 'zhcom' WHERE developer_id IS NULL")
    for row in conn.execute("SELECT DISTINCT project_id, project_name FROM houses"):
        conn.execute(
            """
            INSERT INTO projects (id, developer_id, name, region, created_at, updated_at)
            VALUES (?, 'zhcom', ?, ?, ?, ?)
            ON CONFLICT(id) DO NOTHING
            """,
            (row["project_id"], row["project_name"], CITY, now, now),
        )
    tags = [
        ("евроформат", ""),
        ("кухня-гостиная", ""),
        ("изолированные комнаты", ""),
        ("мастер-спальня", ""),
        ("гардеробная", ""),
        ("два санузла", ""),
        ("раздельный санузел", ""),
        ("лоджия", ""),
        ("балкон", ""),
        ("окно в ванной", ""),
        ("угловая квартира", ""),
        ("распашонка", ""),
        ("линейная планировка", ""),
        ("длинный коридор", ""),
        ("большая прихожая", ""),
        ("компактная кухня", ""),
        ("кухня-ниша", ""),
        ("окна на одну сторону", ""),
        ("окна на две стороны", ""),
    ]
    conn.executemany(
        """
        INSERT INTO layout_tags (name, description)
        VALUES (?, ?)
        ON CONFLICT(name) DO NOTHING
        """,
        tags,
    )


def start_run() -> int:
    with connect() as conn:
        now = datetime.now().isoformat(timespec="seconds")
        if conn.backend == "sqlite":
            cur = conn.execute(
                "INSERT INTO refresh_runs (started_at, status) VALUES (?, ?)",
                (now, "running"),
            )
            return int(cur.lastrowid)
        row = conn.execute(
            "INSERT INTO refresh_runs (started_at, status) VALUES (?, ?) RETURNING id",
            (now, "running"),
        ).fetchone()
        return int(row["id"])


def finish_run(run_id: int, status: str, message: str, source_total: int, collected_total: int) -> None:
    with connect() as conn:
        conn.execute(
            """
            UPDATE refresh_runs
            SET finished_at = ?, status = ?, message = ?, source_total = ?, collected_total = ?
            WHERE id = ?
            """,
            (
                datetime.now().isoformat(timespec="seconds"),
                status,
                message,
                source_total,
                collected_total,
                run_id,
            ),
        )


def replace_data(
    houses: Iterable[House],
    flats: Iterable[Flat],
    groups: Iterable[Dict[str, Any]],
    developer_id: str = "zhcom",
    developer_name: str = COMPETITOR,
    developer_type: str = "competitor",
    source_url: str = "https://zhcom.ru/flats",
    source: str = "zhcom",
) -> int:
    houses = list(houses)
    flats = list(flats)
    groups = list(groups)
    now = datetime.now().isoformat(timespec="seconds")

    with connect() as conn:
        conn.execute(
            """
            INSERT INTO developers (id, name, type, region, source_url, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(id) DO UPDATE SET
                name = excluded.name,
                type = excluded.type,
                region = excluded.region,
                source_url = excluded.source_url,
                updated_at = excluded.updated_at
            """,
            (developer_id, developer_name, developer_type, CITY, source_url, now, now),
        )
        snapshot_id = _create_snapshot(conn, developer_id, source, now, houses, flats, groups)

        existing_project_ids = [
            row["id"] for row in conn.execute("SELECT id FROM projects WHERE developer_id = ?", (developer_id,))
        ]
        if existing_project_ids:
            placeholders = _placeholders(len(existing_project_ids))
            conn.execute(f"DELETE FROM houses WHERE project_id IN ({placeholders})", existing_project_ids)
        conn.execute("DELETE FROM layout_groups WHERE developer_id = ?", (developer_id,))

        project_rows = {}
        for house in houses:
            project_rows[house.project_id] = (
                house.project_id,
                developer_id,
                house.project_name,
                CITY,
                now,
                now,
            )
        conn.executemany(
            """
            INSERT INTO projects (id, developer_id, name, region, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(id) DO UPDATE SET
                name = excluded.name,
                region = excluded.region,
                updated_at = excluded.updated_at
            """,
            list(project_rows.values()),
        )

        conn.executemany(
            """
            INSERT INTO houses (house_id, project_id, project_name, house_name)
            VALUES (?, ?, ?, ?)
            """,
            [(h.house_id, h.project_id, h.project_name, h.house_name) for h in houses],
        )
        counts_by_house: Dict[str, int] = {}
        for flat in flats:
            counts_by_house[flat.house_id] = counts_by_house.get(flat.house_id, 0) + 1
        conn.executemany(
            """
            INSERT INTO buildings (id, project_id, name, source_id, total_apartments_collected, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(id) DO UPDATE SET
                project_id = excluded.project_id,
                name = excluded.name,
                source_id = excluded.source_id,
                total_apartments_collected = excluded.total_apartments_collected,
                updated_at = excluded.updated_at
            """,
            [
                (h.house_id, h.project_id, h.house_name, h.house_id, counts_by_house.get(h.house_id, 0), now, now)
                for h in houses
            ],
        )

        previous_active_ids = {
            row["flat_id"]
            for row in conn.execute(
                "SELECT flat_id FROM flats WHERE developer_id = ? AND status = 'in_sale'",
                (developer_id,),
            )
        }
        current_ids = {flat.flat_id for flat in flats}

        conn.executemany(
            """
            INSERT INTO flats (
                flat_id, developer_id, code, project_id, project_name, house_id, house_name, rooms,
                area, floor, price, price_per_sqm, status, url, image_url, layout_uuid,
                first_seen_at, last_seen_at, created_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'in_sale', ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(flat_id) DO UPDATE SET
                developer_id = excluded.developer_id,
                code = excluded.code,
                project_id = excluded.project_id,
                project_name = excluded.project_name,
                house_id = excluded.house_id,
                house_name = excluded.house_name,
                rooms = excluded.rooms,
                area = excluded.area,
                floor = excluded.floor,
                price = excluded.price,
                price_per_sqm = excluded.price_per_sqm,
                status = 'in_sale',
                url = excluded.url,
                image_url = excluded.image_url,
                layout_uuid = excluded.layout_uuid,
                last_seen_at = excluded.last_seen_at,
                updated_at = excluded.updated_at
            """,
            [
                (
                    f.flat_id,
                    developer_id,
                    f.code,
                    f.project_id,
                    f.project_name,
                    f.house_id,
                    f.house_name,
                    f.rooms,
                    f.area,
                    f.floor,
                    f.price,
                    _price_per_sqm(f.price, f.area),
                    f.url,
                    f.image_url,
                    f.layout_uuid,
                    now,
                    now,
                    now,
                    now,
                )
                for f in flats
            ],
        )
        conn.execute(
            """
            UPDATE flats
            SET status = 'gone_from_exposure', updated_at = ?
            WHERE developer_id = ? AND status = 'in_sale' AND flat_id NOT IN (%s)
            """
            % _placeholders(len(current_ids)),
            (now, developer_id, *current_ids) if current_ids else (now, developer_id),
        ) if current_ids else conn.execute(
            "UPDATE flats SET status = 'gone_from_exposure', updated_at = ? WHERE developer_id = ? AND status = 'in_sale'",
            (now, developer_id),
        )

        conn.executemany(
            """
            INSERT INTO layout_groups (
                group_id, developer_id, project_id, house_id, rooms, layout_no, representative_image_url,
                representative_local_path, hash, flat_count, flat_ids_json, min_area, max_area,
                avg_area, min_price, max_price, avg_price, avg_price_per_sqm, created_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    g["group_id"],
                    developer_id,
                    _project_id_for_group(flats, g),
                    g["house_id"],
                    g["rooms"],
                    g["layout_no"],
                    g["representative_image_url"],
                    g.get("representative_local_path"),
                    g.get("hash"),
                    g["flat_count"],
                    json.dumps(g["flat_ids"], ensure_ascii=False),
                    _min([f.area for f in flats if f.flat_id in set(g["flat_ids"])]),
                    _max([f.area for f in flats if f.flat_id in set(g["flat_ids"])]),
                    _avg([f.area for f in flats if f.flat_id in set(g["flat_ids"])]),
                    _min([f.price for f in flats if f.flat_id in set(g["flat_ids"])]),
                    _max([f.price for f in flats if f.flat_id in set(g["flat_ids"])]),
                    _avg([f.price for f in flats if f.flat_id in set(g["flat_ids"])]),
                    _avg([_price_per_sqm(f.price, f.area) for f in flats if f.flat_id in set(g["flat_ids"])]),
                    now,
                    now,
                )
                for g in groups
            ],
        )
        for group in groups:
            conn.executemany(
                "UPDATE flats SET layout_group_id = ? WHERE flat_id = ?",
                [(group["group_id"], flat_id) for flat_id in group["flat_ids"]],
            )
        gone_ids = sorted(previous_active_ids - current_ids)
        snapshot_flat_ids = sorted(current_ids | set(gone_ids))
        snapshot_rows = conn.execute(
            """
            SELECT flat_id, price, price_per_sqm, area, floor, status, layout_group_id
            FROM flats
            WHERE flat_id IN (%s)
            """
            % _placeholders(len(snapshot_flat_ids)),
            snapshot_flat_ids,
        ).fetchall() if snapshot_flat_ids else []
        conn.executemany(
            """
            INSERT INTO apartment_snapshots (
                snapshot_id, apartment_id, price, price_per_sqm, area, floor, status, layout_group_id, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    snapshot_id,
                    row["flat_id"],
                    row["price"],
                    row["price_per_sqm"],
                    row["area"],
                    row["floor"],
                    row["status"],
                    row["layout_group_id"],
                    now,
                )
                for row in snapshot_rows
            ],
        )
        return snapshot_id


def _create_snapshot(
    conn: DBConnection,
    developer_id: str,
    source: str,
    now: str,
    houses: List[House],
    flats: List[Flat],
    groups: List[Dict[str, Any]],
) -> int:
    params = (
        developer_id,
        source,
        now,
        "success",
        len({house.project_id for house in houses}),
        len({flat.house_id for flat in flats}),
        len(flats),
        len(groups),
        now,
    )
    if conn.backend == "sqlite":
        cur = conn.execute(
            """
            INSERT INTO snapshots (
                developer_id, source, collected_at, status, projects_count, buildings_count,
                apartments_count, layout_groups_count, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            params,
        )
        return int(cur.lastrowid)
    row = conn.execute(
        """
        INSERT INTO snapshots (
            developer_id, source, collected_at, status, projects_count, buildings_count,
            apartments_count, layout_groups_count, created_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        RETURNING id
        """,
        params,
    ).fetchone()
    return int(row["id"])


def latest_run() -> Dict[str, Any] | None:
    with connect() as conn:
        row = conn.execute(
            "SELECT * FROM refresh_runs ORDER BY id DESC LIMIT 1"
        ).fetchone()
        return dict(row) if row else None


def fetch_report_rows() -> Dict[str, List[Any]]:
    with connect() as conn:
        return {
            "houses": conn.execute("SELECT * FROM houses ORDER BY project_name, house_name").fetchall(),
            "developers": conn.execute("SELECT * FROM developers ORDER BY name").fetchall(),
            "projects": conn.execute("SELECT * FROM projects ORDER BY name").fetchall(),
            "flats": conn.execute(
                """
                SELECT * FROM flats
                WHERE status = 'in_sale' OR status IS NULL
                ORDER BY project_name, house_name, rooms, area
                """
            ).fetchall(),
            "all_flats": conn.execute(
                "SELECT * FROM flats ORDER BY project_name, house_name, rooms, area"
            ).fetchall(),
            "groups": conn.execute(
                "SELECT * FROM layout_groups ORDER BY house_id, rooms, layout_no"
            ).fetchall(),
            "snapshots": conn.execute("SELECT * FROM snapshots ORDER BY collected_at").fetchall(),
            "apartment_snapshots": conn.execute(
                "SELECT * FROM apartment_snapshots ORDER BY created_at, id"
            ).fetchall(),
            "layout_tags": conn.execute("SELECT * FROM layout_tags ORDER BY name").fetchall(),
            "layout_group_tags": conn.execute(
                """
                SELECT lgt.*, lt.name, lt.description
                FROM layout_group_tags lgt
                JOIN layout_tags lt ON lt.id = lgt.tag_id
                ORDER BY lt.name
                """
            ).fetchall(),
            "manual_merges": conn.execute(
                "SELECT * FROM manual_layout_merges ORDER BY created_at, id"
            ).fetchall(),
        }


def create_manual_merge(
    house_id: str,
    rooms: str,
    target_group_key: str,
    source_group_keys: Iterable[str],
    note: str = "",
) -> List[Dict[str, Any]]:
    now = datetime.now().isoformat(timespec="seconds")
    rows = [
        (house_id, rooms, target_group_key, source_group_key, note, now)
        for source_group_key in source_group_keys
        if source_group_key and source_group_key != target_group_key
    ]
    if not rows:
        return []
    with connect() as conn:
        conn.executemany(
            """
            INSERT INTO manual_layout_merges (
                house_id, rooms, target_group_key, source_group_key, note, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(house_id, rooms, target_group_key, source_group_key) DO NOTHING
            """,
            rows,
        )
        return [dict(row) for row in conn.execute("SELECT * FROM manual_layout_merges ORDER BY created_at, id")]


def delete_manual_merge(merge_id: int) -> None:
    with connect() as conn:
        conn.execute("DELETE FROM manual_layout_merges WHERE id = ?", (merge_id,))


def fetch_manual_merges() -> List[Dict[str, Any]]:
    with connect() as conn:
        return [dict(row) for row in conn.execute("SELECT * FROM manual_layout_merges ORDER BY created_at, id")]


def update_layout_tags(layout_group_id: str, tag_ids: Iterable[int]) -> None:
    now = datetime.now().isoformat(timespec="seconds")
    with connect() as conn:
        conn.execute("DELETE FROM layout_group_tags WHERE layout_group_id = ?", (layout_group_id,))
        conn.executemany(
            """
            INSERT INTO layout_group_tags (layout_group_id, tag_id, confidence, source, created_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            [(layout_group_id, int(tag_id), 1.0, "manual", now) for tag_id in tag_ids],
        )


def _price_per_sqm(price: float | None, area: float | None) -> float | None:
    if price is None or not area:
        return None
    return round(float(price) / float(area), 1)


def _avg(values: Iterable[Any]) -> float | None:
    nums = [float(value) for value in values if value is not None]
    return round(sum(nums) / len(nums), 1) if nums else None


def _min(values: Iterable[Any]) -> float | None:
    nums = [float(value) for value in values if value is not None]
    return min(nums) if nums else None


def _max(values: Iterable[Any]) -> float | None:
    nums = [float(value) for value in values if value is not None]
    return max(nums) if nums else None


def _project_id_for_group(flats: List[Flat], group: Dict[str, Any]) -> str:
    ids = set(group["flat_ids"])
    for flat in flats:
        if flat.flat_id in ids:
            return flat.project_id
    return ""
